-- MySQL Script generated by MySQL Workbench
-- Tue Aug 23 14:55:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DEVPLANT_DB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DEVPLANT_DB` ;

-- -----------------------------------------------------
-- Schema DEVPLANT_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DEVPLANT_DB` DEFAULT CHARACTER SET utf8 ;
USE `DEVPLANT_DB` ;

-- -----------------------------------------------------
-- Table `DEVPLANT_DB`.`tipoPlantas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEVPLANT_DB`.`tipoPlantas` ;

CREATE TABLE IF NOT EXISTS `DEVPLANT_DB`.`tipoPlantas` (
  `idtipoPlantas` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(450) NOT NULL,
  PRIMARY KEY (`idtipoPlantas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEVPLANT_DB`.`Plantas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEVPLANT_DB`.`Plantas` ;

CREATE TABLE IF NOT EXISTS `DEVPLANT_DB`.`Plantas` (
  `idPlantas` INT NOT NULL AUTO_INCREMENT,
  `idtipoPlantas` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Costo` FLOAT NULL,
  PRIMARY KEY (`idPlantas`),
  CONSTRAINT `idtipoPlantas`
    FOREIGN KEY (`idtipoPlantas`)
    REFERENCES `DEVPLANT_DB`.`tipoPlantas` (`idtipoPlantas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEVPLANT_DB`.`Stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEVPLANT_DB`.`Stock` ;

CREATE TABLE IF NOT EXISTS `DEVPLANT_DB`.`Stock` (
  `idStock` INT NOT NULL AUTO_INCREMENT,
  `idPlantas` INT NOT NULL,
  `Stock` INT NOT NULL,
  PRIMARY KEY (`idStock`),
  CONSTRAINT `idPlantas`
    FOREIGN KEY (`idPlantas`)
    REFERENCES `DEVPLANT_DB`.`Plantas` (`idPlantas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEVPLANT_DB`.`tipoCuidados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEVPLANT_DB`.`tipoCuidados` ;

CREATE TABLE IF NOT EXISTS `DEVPLANT_DB`.`tipoCuidados` (
  `idtipoCuidados` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(450) NULL,
  PRIMARY KEY (`idtipoCuidados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEVPLANT_DB`.`Cuidados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEVPLANT_DB`.`Cuidados` ;

CREATE TABLE IF NOT EXISTS `DEVPLANT_DB`.`Cuidados` (
  `idPlantas` INT NOT NULL,
  `idtipoCuidados` INT NOT NULL,
  `Periodicidad` INT NULL,
  PRIMARY KEY (`idPlantas`, `idtipoCuidados`),
  CONSTRAINT `fk_cuidados_plantas`
    FOREIGN KEY (`idPlantas`)
    REFERENCES `DEVPLANT_DB`.`Plantas` (`idPlantas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuidados_tipocuidados`
    FOREIGN KEY (`idtipoCuidados`)
    REFERENCES `DEVPLANT_DB`.`tipoCuidados` (`idtipoCuidados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEVPLANT_DB`.`Provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEVPLANT_DB`.`Provincia` ;

CREATE TABLE IF NOT EXISTS `DEVPLANT_DB`.`Provincia` (
  `idProvincia` INT NOT NULL AUTO_INCREMENT,
  `Provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProvincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEVPLANT_DB`.`Localidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEVPLANT_DB`.`Localidad` ;

CREATE TABLE IF NOT EXISTS `DEVPLANT_DB`.`Localidad` (
  `idLocalidad` INT NOT NULL AUTO_INCREMENT,
  `idProvincia` INT NOT NULL,
  `Localidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idLocalidad`, `idProvincia`),
  CONSTRAINT `idProvincia`
    FOREIGN KEY (`idProvincia`)
    REFERENCES `DEVPLANT_DB`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEVPLANT_DB`.`detallePedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEVPLANT_DB`.`detallePedido` ;

CREATE TABLE IF NOT EXISTS `DEVPLANT_DB`.`detallePedido` (
  `iddetallePedido` INT NOT NULL AUTO_INCREMENT,
  `idPedido` INT NOT NULL,
  `idPlantas` INT NOT NULL,
  `Linea` INT NULL,
  `Cantidad` INT NULL,
  `precioUnitario` FLOAT NULL,
  `precioTotal` FLOAT NULL,
  PRIMARY KEY (`iddetallePedido`),
  CONSTRAINT `fk_detallepedido_plantas`
    FOREIGN KEY (`idPlantas`)
    REFERENCES `DEVPLANT_DB`.`Plantas` (`idPlantas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEVPLANT_DB`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEVPLANT_DB`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `DEVPLANT_DB`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `idtipoUsuario` INT NOT NULL,
  `idLocalidad` INT NOT NULL,
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Usuariocol` VARCHAR(45) NULL,
  `eMail` VARCHAR(45) NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NULL,
  `Activo` INT NULL,
  PRIMARY KEY (`idUsuario`),  
  CONSTRAINT `fk_usuario_localidad`
    FOREIGN KEY (`idLocalidad`)
    REFERENCES `DEVPLANT_DB`.`Localidad` (`idLocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_tipousuario`
    FOREIGN KEY (`idtipoUsuario`)
    REFERENCES `DEVPLANT_DB`.`tipoUsuario` (`idtipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEVPLANT_DB`.`tipoUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEVPLANT_DB`.`tipoUsuario` ;

CREATE TABLE IF NOT EXISTS `DEVPLANT_DB`.`tipoUsuario` (
  `idtipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idtipoUsuario`),  
  CONSTRAINT `fk_tipousuario_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `DEVPLANT_DB`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEVPLANT_DB`.`Imagenes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEVPLANT_DB`.`Imagenes` ;

CREATE TABLE IF NOT EXISTS `DEVPLANT_DB`.`Imagenes` (
  `idImagenes` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `idPlantas` INT NULL,
  PRIMARY KEY (`idImagenes`),
  CONSTRAINT `fk_imagenes_plantas`
    FOREIGN KEY (`idPlantas`)
    REFERENCES `DEVPLANT_DB`.`Plantas` (`idPlantas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEVPLANT_DB`.`Factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEVPLANT_DB`.`Factura` ;

CREATE TABLE IF NOT EXISTS `DEVPLANT_DB`.`Factura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `iddetallePedido` INT NULL,
  `idUsuario` INT NULL,
  `total` FLOAT NULL,
  PRIMARY KEY (`idFactura`),
  CONSTRAINT `iddetallePedido`
    FOREIGN KEY (`iddetallePedido`)
    REFERENCES `DEVPLANT_DB`.`detallePedido` (`iddetallePedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `DEVPLANT_DB`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
